server:
  port: 8004
spring:
  application:
    name: orders-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8889/eureka/,http://localhost:8888/eureka/
    fetch-registry: true
    register-with-eureka: true
    #心跳检测与续约时间
    #测试时将值设置小些，保证服务关闭后注册中心能及时提出服务
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳之后等待的时间上线，单位为秒，超过则剔除
    lease-expiration-duration-in-seconds: 2
